# Generated by Django 5.0.6 on 2025-04-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountentry',
            options={'verbose_name': 'Account Entry', 'verbose_name_plural': 'Account Entries'},
        ),
        migrations.RemoveField(
            model_name='accountentry',
            name='created',
        ),
        migrations.AddField(
            model_name='accountentry',
            name='name',
            field=models.CharField(default=12, help_text='Name of this account entry', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountentry',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='The permissions this account entry grants', to='auth.permission', verbose_name='permissions'),
        ),
    ]
