# Generated by Django 5.0.6 on 2025-04-30 04:21
from django.db import migrations, models


#Create new migration for accounts
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountentry_options_and_more'), 
    ]

#operations list to use in the migration
    operations = [
        migrations.CreateModel(   #new model called Team
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
