# Generated by Django 5.0.6 on 2025-04-30 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountentry',
            options={'verbose_name': 'Employees', 'verbose_name_plural': 'Employee Entry'},
        ),
    ]
