# Generated by Django 5.0.6 on 2025-04-30 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveysubmission',
            name='user',
        ),
        migrations.CreateModel(
            name='HealthVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100)),
                ('session_date', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('q1_vote', models.CharField(max_length=10)),
                ('q1_feedback', models.TextField(blank=True)),
                ('q1_team_actions', models.TextField(blank=True)),
                ('q1_org_solutions', models.TextField(blank=True)),
                ('q2_vote', models.CharField(max_length=10)),
                ('q2_feedback', models.TextField(blank=True)),
                ('q2_team_actions', models.TextField(blank=True)),
                ('q2_org_solutions', models.TextField(blank=True)),
                ('q3_vote', models.CharField(max_length=10)),
                ('q3_feedback', models.TextField(blank=True)),
                ('q3_team_actions', models.TextField(blank=True)),
                ('q3_org_solutions', models.TextField(blank=True)),
                ('q4_vote', models.CharField(max_length=10)),
                ('q4_feedback', models.TextField(blank=True)),
                ('q4_team_actions', models.TextField(blank=True)),
                ('q4_org_solutions', models.TextField(blank=True)),
                ('q5_vote', models.CharField(max_length=10)),
                ('q5_feedback', models.TextField(blank=True)),
                ('q5_team_actions', models.TextField(blank=True)),
                ('q5_org_solutions', models.TextField(blank=True)),
                ('q6_vote', models.CharField(max_length=10)),
                ('q6_feedback', models.TextField(blank=True)),
                ('q6_team_actions', models.TextField(blank=True)),
                ('q6_org_solutions', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SurveyAnswer',
        ),
        migrations.DeleteModel(
            name='SurveySubmission',
        ),
    ]
